Repository BhuvanArn/LastChance---AREA, pull requests merged in 2025-01, with the labels that each got.

#46 AREA-89 :sparkles: 💚 New CI `tests_run` job
  .github/workflows/actions.yaml
  client/Dockerfile
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/App.vue
  client/src/router/index.js
  client/src/views/Login.vue
  client/test/Login.test.js
  client/tests.sh
  client/vite.config.js
  client/vue.config.js
  docker-compose.yml
Labels: enhancement

#51 Update action reaction base
  data/service_storage/services.yml
  lib/protocol/__init__.py
  lib/service_mod/timer/__init__.py
  lib/serviceconf/__init__.py
  services/action/main.py
  services/advanced/Dockerfile
  services/reaction/main.py
Labels: bug, enhancement

#55 🐛 fix crash action reaction when no endpoint/middeware/strategy
  lib/serviceconf/__init__.py
Labels: bug

#63 Add security for nonstring cache datas saving
  services/action/main.py
Labels: enhancement

#67 AREA-14 :sparkles: New service page
  .github/workflows/actions.yaml
  client/package-lock.json
  client/package.json
  client/src/components/AddServiceModal.vue
  client/src/components/CreateAreaModal.vue
  client/src/components/SectionList.vue
  client/src/components/SectionListMobile.vue
  client/src/components/TableAreas.vue
  client/src/components/WidgetList.vue
  client/src/components/WorkspaceNavBar.vue
  client/src/views/Login.vue
  client/src/views/MobileServicePage.vue
  client/src/views/ServicePage.vue
  docker-compose.yml
  services/advanced/ActionReactionService/AddActionEventHandler.cs
  services/advanced/ActionReactionService/GetServicesEventHandler.cs
  services/advanced/AdvancedServices/Controllers/AuthController.cs
  services/router/routes.yml
  services/router/src/main.rs
  services/swagger/index.js
  services/swagger/routes.yml
Labels: enhancement

#71 🐛 fix bug db updating
  lib/protocol/__init__.py
  services/action/main.py
  services/reaction/main.py
  services/router/src/main.rs
Labels: bug

#88 ✨ change way json is read
  services/action/main.py
  services/reaction/main.py
Labels: bug

#95 🐛 fix signal sigterm handling
  services/action/main.py
  services/reaction/main.py
Labels: bug
